version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-zgr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zgrpass}
      POSTGRES_DB: ${POSTGRES_DB:-zgrwise}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./tools/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zgr} -d ${POSTGRES_DB:-zgrwise}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6380:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build: ./apps/api
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - OLLAMA_BASE=${OLLAMA_BASE}
      - API_KEY=${API_KEY}
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
      ollama: { condition: service_healthy }
    ports: ["8000:8000"]
    volumes:
      - ./apps/api:/app
      - ./data/exports:/data/exports

  worker:
    build: ./apps/worker
    command: python -m worker.main
    depends_on: [api, redis, db]
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - OLLAMA_BASE=${OLLAMA_BASE}
    volumes:
      - ./apps/worker:/worker
      - ./data/exports:/data/exports

  web:
    build: ./apps/web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      api: { condition: service_started }
    ports: ["3000:3000"]
    volumes:
      - ./apps/web:/app

  scheduler:
    build: ./apps/worker
    command: python -m worker.scheduler
    depends_on: [api, worker, redis, db]
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - OLLAMA_BASE=${OLLAMA_BASE}
    volumes:
      - ./apps/worker:/worker

volumes:
  db_data:
  ollama_data:
  exports: 